version: '3.3'

services:
  database:
    container_name: database
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: example
    ports:
      - 5432:5432
