version: '3.3'

services:
  database:
    container_name: database
    hostname: postgres
    build: .
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: test
    ports:
      - 5432:5432
    entrypoint: "sh -c /entrypoint.sh"
